name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PORT: ${{secrets.PORT}}
  DB_URI_APP: ${{secrets.DB_URI_APP}}

  ORIGIN_CLIENT: ${{secrets.ORIGIN_CLIENT}}
  ORIGIN_WORKER: ${{secrets.ORIGIN_WORKER}}
  ORIGIN_3: ${{secrets.ORIGIN_3}}
  
  JWT_EXPIRE: ${{secrets.JWT_EXPIRE}}
  JWT_SECREATE: ${{secrets.JWT_SECREATE}}
  
  REDIS_PORT: ${{secrets.REDIS_PORT}}
  REDIS_URI: ${{secrets.REDIS_URI}}
  REDIS_USERNAME: ${{secrets.REDIS_USERNAME}}
  REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test
    - name: Build the Docker image
      run: docker build -t guruji-astro .
    - name: tagging docker image
      run: docker tag guruji-astro ritesh001/guruji-astro
    - name: docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: push docker image
      run: docker push ritesh001/guruji-astro
